// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	endpoint "github.com/beoneill/gokittest/flights/pkg/endpoint"
	pb "github.com/beoneill/gokittest/flights/pkg/grpc/pb"
	grpc "github.com/go-kit/kit/transport/grpc"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	health grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.FlightsServer {
	return &grpcServer{health: makeHealthHandler(endpoints, options["Health"])}
}
